import type { Book, BookContainer, LibraryState } from "./types";

const seedContainers: BookContainer[] = [
  { id: "busta-1", name: "Busta 1", color: "coral" }, { id: "busta-2", name: "Busta 2", color: "sky" },
  { id: "busta-3", name: "Busta 3", color: "sun" }, { id: "scatola", name: "Scatola", color: "violet" },
  { id: "libreria", name: "Libreria", color: "mint" },
];
const titles: Record<string, string[]> = {
  "busta-1": ["Leggende e fiabe","Giovani poeti sudamericani","Romanzi - Hesse","Paull'Italia [?]","Imparo a disegnare gli animali","Imparo a dipingere e disegnare","Antifurto","Gesti & segni per comunicare [?]","Marina Bellezza","Racconti con colonna sonora","Opinioni di un clown","Viaggio a Saint Kilda","La cultura dell'educazione","Gianni Tonveron [?]","La leggenda di Bena Stemma [?]","La finestra vuota","I 3M [?]","Puzzle","La pergamena del seducente [?]","Campi tra spazio e pacchetto [?]","Il cuore melomane [?]","Quando Zumpi prese mio [?]","La colpa viene facciata [?]","La svolta di Babele","Angelus Novus","Il prisma del io narrante"],
  "busta-2": ["Battato biglietto [?]","Rimpianti T [?]","Il gene della matematica","Memoriale di ma ria mono [?]","Destinati un'ancelle [?]","Nessuna cortesia all'uscita","Arduino","Fieno falciato","Non ti muovere","Alberto Arbasino","Morte a Torino","Manuale elettronica","Inchiostro di Jack","Cronache dalla ditta","Il curioso caso del pentino [?]","The Arbasino down [?]","I semi del male","I pesci non chiudono gli occhi","Io Pentiendo [?]","Una nuvola come tappeto","L'annata dei cigni bianchi","La verita dell'alligatore (Carlo) [?]","La verita dell'alligatore (Marrone) [?]","Il linguaggio della matematica","Scusate il disturbo","Scrivere e comunicare","Come una bestia feroce","Animal Factory","Pellicani, uccelli commestibili","Convivere il pensiero [?]","Tonto scarpo lo stesso [?]","Con gli occhi del nemico","Una vita sottile","Laboratorio scrittura scuola","L'impronta del lupo","Il giudice dei dannati","Gorilla","Tropico","La famiglia casa"],
  "busta-3": ["Guandami + Forte [?]","Shantala","Morte a domicilio","44 gatti in noir","Ragazze per sempre","La resa del leone","Strade strappate","Sardinia blues","Manicomio primavera","Il filo infinito","Poeti siciliani del '900","Scapigliata, lisciata","Creiamo cultura insieme","Piombo fuso","Castelli valdostani","La decrescita felice","Virgole per caso","Il tempo della strega","La ragazza porcospino","Lettere alla fidanzata","Si fermi qui","Il viaggio di ritorno","Short Stories","L'eco della mente","Il re del crimine","Che tu per me sia il coltello","Il mondo delle cose senza nome","Il cervello irriverente","La loquacita sottosopra [?]","Le colpe dei padri","Guida castelli piemontesi","Emilio","He & A [?]","Il tramonto birmano","Piccoli racconti di un'infinita...","Una luce passeggera","Sergente Getulio","Il cosmo secondo Agnetha","L'eta della ragione","Le indagini di Kento Tanaka","Qualche buona ragione per sparire...","Quando verra la rivoluzione...","Sinistri","Il nipote di Wittgenstein","La ballata di Borgo San Paolo","Qui c'e tutto il mondo","Negli occhi di Timea","Per non rischiare!","L'anno senza estate","Morbose fantasie","Dove le ragioni finiscono","I volatori nella macchina","Il fantasma di Zapata","L'odore della polvere da sparo","L'assassino degli scacchi","Handicap e sessualita...","Mai piu pene ne oblio [?]","Fuori registro","Vuoto centrale","Niente mi basta","Casi clinici 1","7 storie gotiche","Il significato del disegno infantile","Under cover","Psicologia dell'handicap...","Thermos","LOL","Borsa Olimpiadi","Le carte delle parole da scoprire"],
  scatola: ["Il pallino della matematica","La bambina e il robottone","Ragazze","Piccolo mondo antico","La ventisettesima citta","Il linguaggio infantile","Competenze comunicative e linguistiche","Cronaca nera mon amour","Il graffio fonetico","Ressa come una ciliegia [?]","Emozioni e sentimenti","Hermann Hesse - Il mio credo","Lottare per un minuto","Leggende napoletane","Nel posto sbagliato"],
  libreria: ["La citta dei vivi","L'eta del malessere","I giardini dei dissidenti","La voce","La penombra che abbiamo attraversato","Vita di Emily Dickinson","Voti di Mykhaulyk [?]","Cielo nero","La signora in verde","Un doppio sospetto","Piu sporco della neve","Registro di classe","Una pistola come la tua","Il circolo abbandonato","Metallo","La donna di troppo","Pessime scuse per un massacro","Il senso del dolore","Lo sentimentalismo","Hotel Silence","Piu bambi [?]","La fiamma cadente queste [?]","Non lasciarmi","Il segreto della montagna","Persi d'amore","McElli, Pano + Hesse [?]","La doppia vita dei numeri","I doppi abissi di Chagall [?]","La ballata del re di Dinamo [?]","Manu chiamano [?]","Il torrente dei diavoli","Maratti - Hesse [?]","Il tempo delle donne","Chetosene [?]","Il fantasma di Mozart","Notti fiorentine","L'enigma di Flatey","Ida","Never Quiet","Lettres persanes","Manuale per apprendisti maghi","La strana pelle dei... [?]","La ragazza con parafulmine [?]","Vecchio amico non dimenticato","Senza la citta [?]","Un corpo nel lago","Un caso archiviato","Come siamo diventati marocchini","Anche se sei il mio custode","Parole di pesci rossi","L'attentato"],
};
const seedBooks: Book[] = Object.entries(titles).flatMap(([containerId, items]) => items.map((rawTitle, index) => ({ id: `${containerId}-${index + 1}`, title: rawTitle.replace(" [?]", ""), containerId, status: "available" as const, uncertain: rawTitle.endsWith("[?]"), createdAt: "2026-08-18T00:00:00.000Z" })));
export const initialLibraryState: LibraryState = { books: seedBooks, containers: seedContainers };
